Ui/WebStore/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebStore.DomainNew.Filters;
using WebStore.DomainNew.ViewModels;
using WebStore.Interfaces;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IProductService _productService;
        private readonly IConfiguration _configuration;

        public CatalogController(IProductService productService, IConfiguration configuration)
        {
            _productService = productService;
            _configuration = configuration;
        }

        public IActionResult Shop(int? sectionId, int? brandId, int page = 1)
        {
            var pageSize = int.Parse(_configuration["PageSize"]);
            var products = GetProducts( sectionId,  brandId,  page, out var totalCount);

           

            // сконвертируем в CatalogViewModel
            var model = new CatalogViewModel()
            {
                BrandId = brandId,
                SectionId = sectionId,
                Products = products,
                PageViewModel =new PageViewModel
                {
                    PageSize=pageSize,
                    PageNumber=page,
                    TotalItems=totalCount
                }
             };

            return View(model);
        }
        public IActionResult GetFilteredItems(int? sectionId, int? brandId, int page = 1)
        {
            var productsModel = GetProducts(sectionId, brandId, page, out var totalCount);
            return PartialView("Partial/FeaturedItems", productsModel);
        }

        private IEnumerable<PageViewModel> GetProducts(int? sectionId, int? brandId, int page, out object totalCount)
        {
            var products = _productService.GetProducts(
              new ProductFilter
              {
                  SectionId = sectionId,
                  BrandId = brandId,
                  Page = page,
                  PageSize = int.Parse(_configuration["PageSize"])
              });
            totalCount = products.TotalCount;
            return products.Products.Select(p => new ProductViewModel()
            {
                Id = p.Id,
                ImageUrl = p.ImageUrl,
                Name = p.Name,
                Order = p.Order,
                Price = p.Price,
                BrandName = p.Brand?.Name ?? String.Empty
            }).OrderBy(p => p.Order)
           .ToList();
    }

        public IActionResult ProductDetails(int id)
        {
            var product = _productService.GetProductById(id);
            if (product == null)
                return NotFound();

            return View(new ProductViewModel
            {
                Id = product.Id,
                ImageUrl = product.ImageUrl,
                Name = product.Name,
                Order = product.Order,
                Price = product.Price,
                BrandName = product.Brand?.Name ?? string.Empty
            });
        }
    }
}

Ui/WebStore/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.DomainNew.ViewModels;
using WebStore.Interfaces;

namespace WebStore.Controllers
{
    [Route("users")]
    [Authorize]
    public class EmployeeController : Controller
    {
        public IEmployeesData _employees { get; }

        public EmployeeController(IEmployeesData employees)
        {
            _employees = employees;
        }

        [Route("all")]
        [AllowAnonymous]
        public IActionResult Index()
        {
            //return new HttpNotAuthorizedResult();
            //return StatusCode(500);
            //return new RedirectResult("");
            //return new RedirectToActionResult();
            //return new PartialViewResult();
            //return new JsonResult("");
            //return new NotFoundResult();
            //return new FileContentResult();        
            //return new EmptyResult();
            //return new ContentResult();

            //return View("Details", _employees);
            return View(_employees.GetAll());
        }

        [Route("{id}")]
        public IActionResult Details(int id)
        {
            //throw new ApplicationException("Что-то пошло не так...");

            // Получаем сотрудника по Id
            var employee = _employees.GetById(id);

            // Если такого не существует
            if (employee == null)
                return NotFound();// возвращаем результат 404 Not Found

            // Иначе возвращаем сотрудника
            return View(employee);
        }

        [HttpGet]
        [Route("edit/{id?}")]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return View(new EmployeeView());
            }

            EmployeeView model = _employees.GetById(id.Value);
            if (model == null)
            {
                return NotFound();// возвращаем результат 404 Not Found
            }

            return View(model);
        }

        [HttpPost]
        [Route("edit/{id?}")]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(EmployeeView model)
        {
            if (model.Age < 18 || model.Age > 100)
            {
                ModelState.TryAddModelError("Age", "Пользователь должен быть совершеннолетним");
            }

            if (!ModelState.IsValid) // Проверяем модель на валидность
            {
                return View(model);
            }

            if (model.Id > 0) // если есть Id, то редактируем модель
            {
                var dbItem = _employees.GetById(model.Id);

                if (ReferenceEquals(dbItem, null))
                    return NotFound();// возвращаем результат 404 Not Found

                dbItem.FirstName = model.FirstName;
                dbItem.SurName = model.SurName;
                dbItem.Age = model.Age;
                dbItem.Patronymic = model.Patronymic;
            }
            else // иначе добавляем модель в список
            {
                _employees.AddNew(model);
            }

            _employees.Commit(); // станет актуальным позднее (когда добавим БД)

            return RedirectToAction(nameof(Index));
        }

        [Route("delete/{id}")]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            _employees.Delete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Ui/WebStore/Views/Shared/_Footer.cshtml
<footer id="footer">
    <!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2><span>e</span>-shopper</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe1.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe2.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe3.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe4.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="~/images/home/map.png" alt="" />
                        <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Service</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Online Help</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Change Location</a></li>
                            <li><a href="#">FAQ’s</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Quock Shop</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">T-Shirt</a></li>
                            <li><a href="#">Mens</a></li>
                            <li><a href="#">Womens</a></li>
                            <li><a href="#">Gift Cards</a></li>
                            <li><a href="#">Shoes</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Policies</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Privecy Policy</a></li>
                            <li><a href="#">Refund Policy</a></li>
                            <li><a href="#">Billing System</a></li>
                            <li><a href="#">Ticket System</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Company Information</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Store Location</a></li>
                            <li><a href="#">Affillate Program</a></li>
                            <li><a href="#">Copyright</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Your email address" />
                            <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                            <p>Get the most recent updates from <br />our site and be updated your self...</p>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
                <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
            </div>
        </div>
    </div>

</footer><!--/Footer-->

Ui/WebStore/Views/Shared/_Header.cshtml
<header id="header">
    <!--header-->
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="logo pull-left">
                        <a asp-controller="Home" asp-action="Index">
                            <img src="~/images/home/logo.png" alt="" />
                        </a>
                    </div>
                    <div class="pull-right" id="cartContainer">
                        @await Component.InvokeAsync("CartSummary")
                    </div>
                </div>

                <div class="col-sm-3">
                    @await Component.InvokeAsync("LoginLogout")
                </div>
            </div>
        </div>
    </div>
    <!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a is-active-route asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="dropdown">
                                <a is-active-route ignore-action asp-controller="Catalog" asp-action="Shop">Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a asp-controller="Catalog" asp-action="Shop">Products</a></li>
                                    <li><a asp-controller="Catalog" asp-action="ProductDetails">Product Details</a></li>
                                    <li><a asp-controller="Home" asp-action="Checkout">Checkout</a></li>
                                    <li><a asp-controller="Home" asp-action="Cart">Cart</a></li>
                                    <li><a asp-controller="Home" asp-action="Login">Login</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a is-active-route asp-controller="Home" asp-action="Blog">Blog<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a asp-controller="Home" asp-action="Blog">Blog List</a></li>
                                    <li><a asp-controller="Home" asp-action="BlogSingle">Blog Single</a></li>
                                </ul>
                            </li>
                            <li><a is-active-route asp-controller="Home" asp-action="NotFound">404</a></li>
                            <li><a is-active-route asp-controller="Home" asp-action="ContactUs">Contact</a></li>
                            <li><a is-active-route ignore-action asp-controller="Employee" asp-action="Index">Employees</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search" />
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

Ui/WebStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet">

    <environment include="Development">
        <link href="~/css/prettyPhoto.css" rel="stylesheet">
        <link href="~/css/price-range.css" rel="stylesheet">
        <link href="~/css/animate.css" rel="stylesheet">
        <link href="~/css/responsive.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link href="~/css/site.min.css" rel="stylesheet">
    </environment>


    <link href="~/css/main.css" rel="stylesheet">

    <!--Секция для отображения кастомных стилей, если понадобятся-->
    @RenderSection("styles", false)
    <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    @await Html.PartialAsync("_Header")

    <div class="container">
        @RenderBody()
    </div>

    @await Html.PartialAsync("_Footer")

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/jquery.scrollUp.min.js"></script>

    <environment include="Development">
        <script src="~/js/price-range.js"></script>
        <script src="~/js/jquery.prettyPhoto.js"></script>
        <script src="~/js/main.js"></script>
        <script src="~/js/cartLogic.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(function() {
            Cart.init({
                addToCartLink: '@Url.Action("AddToCart","Cart")',
                getCartViewLink: '@Url.Action("GetCartView","Cart")',
                removeFromCartLink: '@Url.Action("RemoveFromCart","Cart")',
                ​ decrementLink​ : ​ '@Url.Action("DecrementFromCart","Cart")'
            });
        })
    </script>

    <!--Секция для отображения кастомных скриптов, если понадобятся-->
    @RenderSection("scripts", false)
</body>
</html>

Ui/WebStore/Views/Shared/_LayoutBreadcrumbs.cshtml
@using WebStore.DomainNew.ViewModels
@{
    Layout = "_Layout";

    var type = Context.Request.Query.ContainsKey("sectionId")
        ? BreadCrumbType.Section
        : Context.Request.Query.ContainsKey("brandId")
            ? BreadCrumbType.Brand
            : BreadCrumbType.None;

    var fromType = BreadCrumbType.Section;

    // Если это метод деталей товара
    if ((string)ViewContext.RouteData.Values["action"] == "ProductDetails")
    {
        // Устанавливаем тип товара
        type = BreadCrumbType.Item;
    }

    var id = 0;

    switch (type)
    {
        case BreadCrumbType.None:
            break;
        case BreadCrumbType.Section:
            id = int.Parse(Context.Request.Query["sectionId"].ToString());
            break;
        case BreadCrumbType.Brand:
            id = int.Parse(Context.Request.Query["brandId"].ToString());
            break;
        case BreadCrumbType.Item:
            // Если есть ключ того, что пришли с бренда,
            // ставим источник – бренд
            if (Context.Request.Query.ContainsKey("fromBrand"))
            {
                fromType = BreadCrumbType.Brand;
            }
            id = int.Parse(ViewContext.RouteData.Values["id"].ToString());
            break;
        default:
            throw new ArgumentOutOfRangeException();
    }

}

@(await @Component.InvokeAsync("BreadCrumbs", new {type, id, fromType}))

@RenderBody()
@section scripts{ 
    @RenderSection("scripts",false)
}